/* $OpenBSD: version.h,v 1.102 2024/07/01 04:31:59 djm Exp $ */

#define SSH_WINDOWS_VERSION "OpenSSH_9.8"
#define SSH_WINDOWS_BANNER " Win32-OpenSSH-GitHub"
#define SSH_VERSION	SSH_WINDOWS_VERSION

#define SSH_PORTABLE	"p1.2"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE
